name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DJANGO_DEBUG: 'false'
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
      SECRET_KEY: 
      SSECRET_KEY_ACTIONS: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checar o código do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Instalar dependências com pipenv
        run: |
          pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Executar migrações do banco de dados
        run: |
          pipenv run python manage.py migrate

      - name: Rodar os testes
        run: |
          pipenv run python manage.py test
